Scrum 24 create home screen: Finished Welcome Back View
GenerateNU/3stones pull request #42
Opened 2024-10-21 07:00 UTC by Dao-Ho

## Description

[[Link to Ticket](insert the link to your JIRA ticket inside the parenthesis here)](https://www.figma.com/design/n4OxYALqlgaK7kxlnq7ilu/3-Stones?node-id=1392-4801&node-type=frame&t=bv7S10Oecp1ZO92v-0)

Added welcome back block to home page

## Screenshots:
![welcome back block finished](https://github.com/user-attachments/assets/aca76c57-6753-4bf9-8c1b-8b8b39cf43e5)

2024-10-21 07:05 UTC, Dao-Ho commented
Update: More accurate notification icon size
![welcome back block finished](https://github.com/user-attachments/assets/c0dd58ba-68d6-46b9-9b15-fbbcfb169627)

2024-10-21 19:42 UTC, rmsap requested changes
Generally good, a few couple comments:

1. Look for places in your TSX where you can extract out to make smaller components. In general seeing something like
```
<View>
     <View>
          <View>
               ...
          </View>
     </View>
</View>
```
is a sign that we may be able to extract out components so that it becomes 
```
<View>
     <View>
          <SomeComponent>
     </View>
</View>
```
or 
<View>
     <SomeComponent>
</View>
This is important because it makes code much easier to read, and consequently much more maintainable in the long run.
2. Can the wide white button and wide green button be combined into a single component that takes in a color prop? Perhaps I missed something but they looked basically identical to me besides the fact that they are a different color, so if we could just have a WideButton prop and then pass in the color that might make the code easier to maintain in the long run.

2024-10-21 19:42 UTC, rmsap commented on frontend/src/screens/home/home.tsx
> +const WelcomeBlock = ({ name }: { name: string }) => {
Maybe this was just here for testing purposes, but can we extract this WelcomeBlock to another file?

2024-10-21 19:42 UTC, rmsap commented on frontend/src/screens/home/home.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Put a comment explaining why you disabled this rule (I'm guessing that the NavigationScreenProp takes in any, any so you didn't have a choice, but good to leave a comment saying that so its documented and future engineers are aware of that).

2024-10-21 19:42 UTC, rmsap commented on frontend/src/screens/home/home.tsx
> +const PortfolioValue = ({
Like above, if we can extract this to another file I think that would be great.

2024-10-23 00:17 UTC, rmsap approved these changes
Great job!

2024-10-23 02:30 UTC, merged